### ISSUE TITLE
启动后崩溃:alaserPGO': double free or corruption

### ISSUE THREAD

**Issue by XiaoJake** [yanliang-wang/FAST_LIO_LC#2]
作者你好

我已经编译完成了(用的c++11才编译成功的),在ubuntu 16.04上,运行如下命令时:
roslaunch aloam_velodyne fastlio_velodyne_VLP_16.launch

遇到了报错:
*** Error in `/home/xiaojake/fast_lio2_lc_ws/devel/lib/aloam_velodyne/alaserPGO': double free or corruption (out): 0x0000000000dd2b60 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fbab1b137e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fbab1b1c37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fbab1b2053c]
/usr/local/lib/libgtsam.so.4(_ZN5gtsam10noiseModel8Diagonal6SigmasERKN5Eigen6MatrixIdLin1ELi1ELi0ELin1ELi1EEEb+0x18d)[0x7fbab53ebe1d]
/usr/local/lib/libgtsam.so.4(+0x114a5d)[0x7fbab5270a5d]
/lib64/ld-linux-x86-64.so.2(+0x106ca)[0x7fbab76d56ca]
/lib64/ld-linux-x86-64.so.2(+0x107db)[0x7fbab76d57db]
/lib64/ld-linux-x86-64.so.2(+0xc6a)[0x7fbab76c5c6a]
======= Memory map: ========
00400000-004a9000 r-xp 00000000 08:01 21208                              /home/xiaojake/fast_lio2_lc_ws/devel/lib/aloam_velodyne/alaserPGO
006a8000-006ac000 r--p 000a8000 08:01 21208                              /home/xiaojake/fast_lio2_lc_ws/devel/lib/aloam_velodyne/alaserPGO
006ac000-006ad000 rw-p 000ac000 08:01 21208                              /home/xiaojake/fast_lio2_lc_ws/devel/lib/aloam_velodyne/alaserPGO
006ad000-006af000 rw-p 00000000 00:00 0 
00d90000-00de3000 rw-p 00000000 00:00 0                                  [heap]
7fba9c000000-7fba9c021000 rw-p 00000000 00:00 0 
7fba9c021000-7fbaa0000000 ---p 00000000 00:00 0 
7fbaa34ce000-7fbaa36ce000 rw-p 00000000 00:00 0 
7fbaa36ce000-7fbaa36d9000 r-xp 00000000 08:01 2107173                    /usr/lib/x86_64-linux-gnu/libjbig.so.0
7fbaa36d9000-7fbaa38d8000 ---p 0000b000 08:01 2107173                    /usr/lib/x86_64-linux-gnu/libjbig.so.0
7fbaa38d8000-7fbaa38d9000 r--p 0000a000 08:01 2107173                    /usr/lib/x86_64-linux-gnu/libjbig.so.0
7fbaa38d9000-7fbaa38dc000 rw-p 0000b000 08:01 2107173                    /usr/lib/x86_64-linux-gnu/libjbig.so.0
7fbaa38dc000-7fbaa38fd000 r-xp 00000000 08:01 136327                     /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fbaa38fd000-7fbaa3afc000 ---p 00021000 08:01 136327                     /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fbaa3afc000-7fbaa3afd000 r--p 00020000 08:01 136327                     /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fbaa3afd000-7fbaa3afe000 rw-p 00021000 08:01 136327                     /lib/x86_64-linux-gnu/liblzma.so.5.0.0

**Comment by yanliang-wang** [comment]
我感觉应该是GTSAM的问题，你的GTSAM是什么版本呢？可以尝试一下[ 4.0.0-alpha2版本](https://github.com/borglab/gtsam/tree/4.0.0-alpha2)

**Comment by XiaoJake** [comment]
> 

我的gtsam版本是 4.0.2, 我按照您说的版本试试, 后面给个反馈

**Comment by XiaoJake** [comment]
> 我感觉应该是GTSAM的问题，你的GTSAM是什么版本呢？可以尝试一下[ 4.0.0-alpha2版本](https://github.com/borglab/gtsam/tree/4.0.0-alpha2)

我的gtsam版本是 4.0.2, 我按照您说的版本试试, 后面给个反馈

**Comment by XiaoJake** [comment]
gtsam安装为  4.0.0-alpha2版本 后启动这个launch后不会报这个错误了.  感谢作者的耐心解答!
但是我现在跑demo包遇到了新的问题,还是没有像范例一样正常跑起来,详情见:
https://github.com/yanliang-wang/FAST_LIO_LC/issues/4#issue-1227535891
