### ISSUE TITLE
fast-lio部分无法正常估计位姿,启动后会反复自转即使真实是静止状态

### ISSUE THREAD

**Issue by XiaoJake** [yanliang-wang/FAST_LIO_LC#3]
我下载了你提供的demo数据集,在编译完成后,在两个终端中分别执行了写到的demo命令:
启动fast-lio:
roslaunch fast_lio mapping_velodyne.launch
播放demo包:
rosbag play '/home/xiaojake/Downloads/T3F2-2021-08-02-15-00-12.bag'

效果是: 看到状态一直在超一个方向自转,无法收敛稳定
刚运行时:
![Screenshot from 2022-04-30 00-16-43](https://user-images.githubusercontent.com/30372147/165983809-11e64d3d-c846-4e48-8c42-e647391fd103.png)
约4s后:
![image](https://user-images.githubusercontent.com/30372147/165983904-2e60be5d-6122-45ed-8d53-93583f4e68c0.png)
每隔几秒:
![image](https://user-images.githubusercontent.com/30372147/165983997-92215d4b-fc42-426a-b9fa-fe10b17dfaec.png)
![image](https://user-images.githubusercontent.com/30372147/165984103-3595ca32-2641-421b-9f9d-311e21d695df.png)

终端中没有提示任何报错信息,刚开始学习这部分代码,一时难以排查,所以向大家请教一下:
![image](https://user-images.githubusercontent.com/30372147/165984347-bb0666dd-33f6-4e7e-a379-587e7a31e405.png)

你们在跑的时候有遇到同样的问题吗?
我是 ubuntu 16.04, 工程用c++11才编译通过的,不知跟这个是否有关

**Comment by XiaoJake** [comment]
尴尬,刚刚提出问题就找到原因了. 作者在readme中就有写到,如果是想单独只测 fast-lio2的效果,需要在launch文件中把
lc_enable变量设置为 false 即可

**Comment by JustThinker** [comment]
我也同样碰到这个问题，如果想使用作者的lc功能，请问要怎么办呢？

**Comment by lwbdegit** [comment]
> 我也同样碰到这个问题，如果想使用作者的lc功能，请问要怎么办呢？

请问解决了吗

**Comment by caotangyu** [comment]
> > 我也同样碰到这个问题，如果想使用作者的lc功能，请问要怎么办呢？
> 
> 请问解决了吗

个人感觉作者写了一个bug
把
if(updateState){
....}  往上移动到kdtree 重建里面就好了
