### ISSUE TITLE
使用测试数据测试出现转圈问题

### ISSUE THREAD

**Issue by JustThinker** [yanliang-wang/FAST_LIO_LC#5]
使用测试数据测试代码，出现转圈问题，并且定位到问题在updateState代码段，检查了pcl为1.8.1，Eigen为3.3.4，请问还有其他依赖会导致出现这个问题吗？

![2022-05-07 12:22:35](https://user-images.githubusercontent.com/20389474/167238062-9eba6412-2dd5-40a1-8baa-b8286010fa59.png)

**Comment by yanliang-wang** [comment]
我这里没遇到过类似的问题, 你单独跑原始的fast-lio可以跑通吗? 将lc_enable设为false测试一下

**Comment by JustThinker** [comment]
设为false可以跑通，我找到原因了，PGO没有正常启动起来导致的这个问题，谢谢作者耐心回复。我将关闭这个issue。
