### ISSUE TITLE
Which IMU did you use?

### ISSUE THREAD

**Issue by Taeyoung96** [yanliang-wang/FAST_LIO_LC#7]
@yanliang-wang   
Hi, Thanks for your great work!  

Your result video mentions that you use Velodyne-VLP 16 channels for LiDAR.  
Then what IMU model did you use?  

Thanks,

**Comment by yanliang-wang** [comment]
Hi, the IMU model of my demo data is Xsens MTi 100.

**Comment by Taeyoung96** [comment]
I got it, thanks for your reply. 😄
