### ISSUE TITLE
Include and library errors 

### ISSUE THREAD

**Issue by rlabs-oss** [yanliang-wang/FAST_LIO_LC#8]
scanRegistration.cpp:44:10: fatal error: opencv/cv.h: No such file or directory
   44 | #include <opencv/cv.h>

src/FAST_LIO_LC/FAST-LIO/include/common_lib.h:8:10: fatal error: fast_lio/Pose6D.h: No such file or directory
    8 | #include <fast_lio/Pose6D.h>

Couldn't build this - while faster_lio and fast_lio2 build fine on the same machine.

**Comment by yanliang-wang** [comment]
Hi, this should be a problem caused by the different OpenCV versions. The version used in the repo is 3.0+. If you are using OpenCV 4, you can try to replace `#include <opencv/cv.h>` with `#include <opencv2/opencv.hpp>`.

**Comment by rlabs-oss** [comment]
Thank you it builds now, but also realize the AVIA Lidar isnt present so some configuration copying from faster_lio maybe needed.
