### ISSUE TITLE
Boost::timer error

### ISSUE THREAD

**Issue by EloyAldao** [yanliang-wang/FAST_LIO_LC#9]
Hi:

I found this error while compiling and I can not get it resolved:
[ 95%] Linking CXX executable /home/developer/catkin/FAST-LIO_LC/devel/lib/aloam_velodyne/alaserPGO
/usr/bin/ld: cannot find -lBoost::timer
collect2: error: ld returned 1 exit status
FAST_LIO_LC/PGO/CMakeFiles/alaserPGO.dir/build.make:476: recipe for target '/home/developer/catkin/FAST-LIO_LC/devel/lib/aloam_velodyne/alaserPGO' failed
make[2]: *** [/home/developer/catkin/FAST-LIO_LC/devel/lib/aloam_velodyne/alaserPGO] Error 1
CMakeFiles/Makefile2:498: recipe for target 'FAST_LIO_LC/PGO/CMakeFiles/alaserPGO.dir/all' failed
make[1]: *** [FAST_LIO_LC/PGO/CMakeFiles/alaserPGO.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

Could you give an advise?
Thanks in advance

**Comment by Huuuaiyuan** [comment]
Hi, how do you solve it
